services:
  - type: web
    name: gestor-pro
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
      - key: APP_LOCALE
        value: es
      - key: APP_FALLBACK_LOCALE
        value: es
      - key: APP_FAKER_LOCALE
        value: es_ES
      - key: APP_TIMEZONE
        value: America/Havana
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: BROADCAST_CONNECTION
        value: log
      - key: FILESYSTEM_DISK
        value: r2
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET
        value: gestor-pro-files
      - key: R2_ENDPOINT
        sync: false
      - key: MAIL_MAILER
        value: resend
      - key: RESEND_API_KEY
        sync: false
      - key: MAIL_FROM_ADDRESS
        value: noreply@gestorpro.app
      - key: MAIL_FROM_NAME
        value: Mi Gestor Pro
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_STACK
        value: single
      - key: LOG_LEVEL
        value: warning
      - key: BCRYPT_ROUNDS
        value: 12
